import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../../components/UI/Header/Header";
import Footer from "../../components/UI/Footer/footer";
import ProviderWrapper from "../../components/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = { 
  title: "Create Next App",
  description: "Generated by create next app",
};

//inside layout.js we have to wrap our redux provider outside of html
//in next js we don't need a browser router like react to route...rather just simply create a folder inside app
// and we can route by /{folder_name}

export default function RootLayout({ children }) {
  return (
    <ProviderWrapper>
    <html lang="en">
      
      <body className="page-container">
        <Header/>
          <div className="content-wrap"> 
            {children}
          </div>
        <Footer/>
      </body>
      
      
    </html>
    </ProviderWrapper>
  );
}
